export interface GalleryPhoto {
  src: string
  alt: string
  category: string
  project: string
  displayProject: string
  location: string
}

export const categories = [
  { slug: 'all', label: 'All' },
  { slug: 'completed', label: 'Completed' },
  { slug: 'interior', label: 'Interior' },
  { slug: 'exterior', label: 'Exterior' },
  { slug: 'framing', label: 'Framing' },
  { slug: 'finishes', label: 'Finishes' },
  { slug: 'renovation', label: 'Renovation' },
  { slug: 'site-foundation', label: 'Site & Foundation' },
]

export const photos: GalleryPhoto[] = [
  // ── ADU Project (32 photos) ──
  { src: '/gallery/adu-exterior.jpg', alt: 'ADU exterior view', category: 'completed', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-exterior-2.jpg', alt: 'ADU exterior alternate angle', category: 'exterior', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-exterior-garage.jpeg', alt: 'ADU garage exterior', category: 'exterior', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-garage.jpeg', alt: 'ADU garage', category: 'exterior', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-garage-3.jpeg', alt: 'ADU garage interior', category: 'exterior', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-kitchen.jpeg', alt: 'ADU kitchen', category: 'interior', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-kitchen-2.jpeg', alt: 'ADU kitchen detail', category: 'interior', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-bedroom.jpeg', alt: 'ADU bedroom', category: 'interior', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-bedroom-barn-door.jpeg', alt: 'ADU bedroom with barn door', category: 'interior', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-entryway.jpeg', alt: 'ADU entryway', category: 'interior', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-bathroom.jpeg', alt: 'ADU bathroom', category: 'finishes', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-bathroom-2.jpeg', alt: 'ADU second bathroom', category: 'finishes', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-shower.jpeg', alt: 'ADU shower', category: 'finishes', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-ceiling-recessed-lighting.jpeg', alt: 'ADU recessed lighting', category: 'finishes', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-ceiling-recessed-lighting-2.jpeg', alt: 'ADU ceiling lighting detail', category: 'finishes', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-repurposed-flooring.jpg', alt: 'ADU repurposed flooring', category: 'finishes', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-framing.jpg', alt: 'ADU framing', category: 'framing', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-interior-framing.jpg', alt: 'ADU interior framing', category: 'framing', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-roof.jpg', alt: 'ADU roof construction', category: 'framing', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-outdoor-interior-roof.jpeg', alt: 'ADU roof from below', category: 'framing', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-foundation.jpg', alt: 'ADU foundation', category: 'site-foundation', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-crawlspace-attic.jpg', alt: 'ADU crawlspace and attic', category: 'framing', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-attic.jpg', alt: 'ADU attic space', category: 'framing', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-blueprints.jpg', alt: 'ADU blueprints', category: 'site-foundation', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-blueprints-2.jpg', alt: 'ADU blueprints detail', category: 'site-foundation', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },
  { src: '/gallery/adu-blueprints-3.jpg', alt: 'ADU blueprints page 3', category: 'site-foundation', project: 'adu-build', displayProject: 'ADU / Guest House', location: 'Mendocino County' },

  // ── Master Suite Remodel (11 photos) ──
  { src: '/gallery/master-suite-perspective.jpeg', alt: 'Master suite overview', category: 'renovation', project: 'master-suite', displayProject: 'Master Suite Remodel', location: 'Mendocino County' },
  { src: '/gallery/master-suite-bathroom.jpeg', alt: 'Master bathroom', category: 'renovation', project: 'master-suite', displayProject: 'Master Suite Remodel', location: 'Mendocino County' },
  { src: '/gallery/master-suite-bathroom-perspective.jpeg', alt: 'Master bathroom wide view', category: 'renovation', project: 'master-suite', displayProject: 'Master Suite Remodel', location: 'Mendocino County' },
  { src: '/gallery/master-suite-bathroom-tub.jpeg', alt: 'Master bathroom soaking tub', category: 'finishes', project: 'master-suite', displayProject: 'Master Suite Remodel', location: 'Mendocino County' },
  { src: '/gallery/master-suite-bathroom-vanity-sinks.jpeg', alt: 'Master bathroom vanity detail', category: 'finishes', project: 'master-suite', displayProject: 'Master Suite Remodel', location: 'Mendocino County' },
  { src: '/gallery/master-suite-shower.jpeg', alt: 'Master suite walk-in shower', category: 'finishes', project: 'master-suite', displayProject: 'Master Suite Remodel', location: 'Mendocino County' },
  { src: '/gallery/master-suite-ceiling-with-beams.jpeg', alt: 'Exposed beam ceiling', category: 'finishes', project: 'master-suite', displayProject: 'Master Suite Remodel', location: 'Mendocino County' },
  { src: '/gallery/master-suite-closet.jpeg', alt: 'Master walk-in closet', category: 'renovation', project: 'master-suite', displayProject: 'Master Suite Remodel', location: 'Mendocino County' },
  { src: '/gallery/master-suite-barn-door.jpeg', alt: 'Barn door detail', category: 'finishes', project: 'master-suite', displayProject: 'Master Suite Remodel', location: 'Mendocino County' },

  // ── Laundry Room Remodel (3 photos) ──
  { src: '/gallery/laundry-room-remodel-cabinets.jpeg', alt: 'Laundry room custom cabinets', category: 'renovation', project: 'laundry-remodel', displayProject: 'Laundry Room Remodel', location: 'Mendocino County' },
  { src: '/gallery/laundry-room-remodel-storage.jpeg', alt: 'Laundry room storage', category: 'renovation', project: 'laundry-remodel', displayProject: 'Laundry Room Remodel', location: 'Mendocino County' },
  { src: '/gallery/laundry-room-sink-and-washing-machine-dryer.jpeg', alt: 'Laundry room sink and appliances', category: 'renovation', project: 'laundry-remodel', displayProject: 'Laundry Room Remodel', location: 'Mendocino County' },

  // ── Round Valley Library (3 photos) ──
  { src: '/gallery/ROUND-VALLEY-LIBRARY-017.jpg', alt: 'Round Valley Library', category: 'completed', project: 'round-valley-library', displayProject: 'Round Valley Library', location: 'Covelo, CA' },
  { src: '/gallery/DSC03783.jpg', alt: 'Library construction', category: 'completed', project: 'round-valley-library', displayProject: 'Round Valley Library', location: 'Covelo, CA' },
  { src: '/gallery/004.jpg', alt: 'Library project', category: 'completed', project: 'round-valley-library', displayProject: 'Round Valley Library', location: 'Covelo, CA' },

  // ── Named Residential Projects ──
  { src: '/gallery/east-elev.-patio-and-sunroom.jpg', alt: 'East elevation — patio and sunroom', category: 'completed', project: 'patio-sunroom', displayProject: 'Patio & Sunroom Addition', location: 'Mendocino County' },
  { src: '/gallery/north-elev..jpg', alt: 'North elevation', category: 'completed', project: 'patio-sunroom', displayProject: 'Patio & Sunroom Addition', location: 'Mendocino County' },
  { src: '/gallery/main-house-2010.jpg', alt: 'Main house circa 2010', category: 'completed', project: 'patio-sunroom', displayProject: 'Patio & Sunroom Addition', location: 'Mendocino County' },
  { src: '/gallery/grasso.jpg', alt: 'Grasso residence', category: 'completed', project: 'grasso-residence', displayProject: 'Grasso Residence', location: 'Mendocino County' },
  { src: '/gallery/arcade-scissor-truss.jpg', alt: 'Arcade scissor truss', category: 'framing', project: 'timber-work', displayProject: 'Timber & Structural Work', location: 'Mendocino County' },
  { src: '/gallery/rafters.jpg', alt: 'Exposed rafters', category: 'framing', project: 'timber-work', displayProject: 'Timber & Structural Work', location: 'Mendocino County' },
  { src: '/gallery/shear.jpg', alt: 'Shear wall construction', category: 'framing', project: 'timber-work', displayProject: 'Timber & Structural Work', location: 'Mendocino County' },
  { src: '/gallery/repurposed-lumber.jpg', alt: 'Repurposed lumber', category: 'finishes', project: 'repurposed-materials', displayProject: 'Repurposed & Reclaimed', location: 'Mendocino County' },
  { src: '/gallery/repurposed-materials.jpg', alt: 'Repurposed building materials', category: 'finishes', project: 'repurposed-materials', displayProject: 'Repurposed & Reclaimed', location: 'Mendocino County' },
  { src: '/gallery/repurposed-wood.jpg', alt: 'Repurposed wood detail', category: 'finishes', project: 'repurposed-materials', displayProject: 'Repurposed & Reclaimed', location: 'Mendocino County' },
  { src: '/gallery/barn-door.jpg', alt: 'Custom barn door', category: 'finishes', project: 'repurposed-materials', displayProject: 'Repurposed & Reclaimed', location: 'Mendocino County' },
  { src: '/gallery/bathroom.jpeg', alt: 'Bathroom renovation', category: 'renovation', project: 'misc-renovation', displayProject: 'Residential Renovations', location: 'Mendocino County' },

  // ── Hero / Showcase Photos (already on site) ──
  { src: '/hero-1.png', alt: 'Contemporary interior with skylights', category: 'interior', project: 'showcase', displayProject: 'Featured Projects', location: 'Sonoma County' },
  { src: '/hero-2.png', alt: 'Vaulted timber beam living room', category: 'interior', project: 'showcase', displayProject: 'Featured Projects', location: 'Ukiah' },
  { src: '/hero-3.png', alt: 'Straw bale and venetian plaster exterior', category: 'completed', project: 'showcase', displayProject: 'Featured Projects', location: 'Mendocino County' },
  { src: '/hero-4.png', alt: 'Rammed earth modern home', category: 'completed', project: 'showcase', displayProject: 'Featured Projects', location: 'Mendocino County' },

  // ── Legacy Project Photos (uncategorized IMG_* series) ──
  { src: '/gallery/IMG_0234.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0256.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0257.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0262.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0263.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0354.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0412-1.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0414-1.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0437.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0444.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0446.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0517.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0603.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0636.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0640.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0750.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0823.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0843.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0920.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0940.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0943.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0944.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0979.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0992.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_0087-1.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1027.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1040.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1042.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1043.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1051.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1122.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1300.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1411.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1447.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1603.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1607.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1618.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1677-1.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1740.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1744.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1745-1.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1761-1.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_1862.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2023.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2031.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2048.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2051.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2053.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2058.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2071.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2076.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2078.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2102.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2104.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2106.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2111.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2205.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2210.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2342.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2346.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2350.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2661.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2662.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2665.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2666.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2676.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2728-4.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2782.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2889.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_2890.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3160.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3164.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3169.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3172.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3179.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3182.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3186.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3190.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3193.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3204.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3213.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3215.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3555.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_3630.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_4858.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_5091.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_5442.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_5466.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_5597.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_5623.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG_7599.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG950248.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG950261.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG950416.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG952335.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG952822.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/IMG952827.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/PICT0002_0001.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/PICT0014_0001.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/Picture_10.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/Picture_101.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/Picture_24.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/Picture_31.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/Picture_94.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/Picture_95.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/DSC_0023.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/018.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/02-16-2006-07_42_58PM.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/0388ED_1-2.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/038AEF1-2.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/038EE31-2.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/039DE81-2.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/100_0386.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/18706.jpeg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/20190926_103631_resized.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/22415.jpeg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/22418.jpeg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/22428.jpeg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
  { src: '/gallery/photo21.jpg', alt: 'Project photo', category: 'completed', project: 'legacy-projects', displayProject: 'Past Projects', location: 'Northern California' },
]
